import { useConfig } from '@/composables/useConfig'

export interface SeoMetaData {
  title?: string
  description?: string | (() => string)
  ogTitle?: string | (() => string)
  ogDescription?: string | (() => string)
  ogType?: 'website' | 'article'
  ogUrl?: string | (() => string)
  twitterCard?: 'summary' | 'summary_large_image'
  twitterTitle?: string | (() => string)
  twitterDescription?: string | (() => string)
}

export function getSeoConfig() {
  const { lguName, labels, siteBrandName, getFullSiteTitle, getOpenGraphUrl } = useConfig()

  const seoData: Record<string, SeoMetaData> = {
    'index': {
      title: getFullSiteTitle('Home'),
      description: () => `Welcome to Better ${lguName.value} — your digital gateway to ${labels.value.lguTypeLabel} of ${lguName.value} services, government information, and community resources.`,
      ogTitle: () => getFullSiteTitle('Home'),
      ogDescription: () => `Welcome to Better ${lguName.value} — your digital gateway to ${labels.value.lguTypeLabel} of ${lguName.value} services, government information, and community resources.`,
      ogType: 'website',
      ogUrl: () => getOpenGraphUrl(),
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Home'),
      twitterDescription: () => `Welcome to Better ${lguName.value} — your digital gateway to ${labels.value.lguTypeLabel} of ${lguName.value} services, government information, and community resources.`,
    },
    'about': {
      title: getFullSiteTitle('About'),
      description: () => `Learn about Better ${lguName.value} — our mission, history, and how ${siteBrandName.value} promotes transparency and accessibility in local governance.`,
      ogTitle: () => getFullSiteTitle('About'),
      ogDescription: () => `Learn about Better ${lguName.value} — our mission, history, and how ${siteBrandName.value} promotes transparency and accessibility in local governance.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}about`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('About'),
      twitterDescription: () => `Learn about Better ${lguName.value} — our mission, history, and how ${siteBrandName.value} promotes transparency and accessibility in local governance.`,
    },
    'accessibility': {
      title: getFullSiteTitle('Accessibility'),
      description: () => `Read our Accessibility Statement. Better ${lguName.value} is committed to ensuring our digital services are accessible to all citizens.`,
      ogTitle: () => getFullSiteTitle('Accessibility'),
      ogDescription: () => `Read our Accessibility Statement. Better ${lguName.value} is committed to ensuring our digital services are accessible to all citizens.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}accessibility`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Accessibility'),
      twitterDescription: () => `Read our Accessibility Statement. Better ${lguName.value} is committed to ensuring our digital services are accessible to all citizens.`,
    },
    'faq': {
      title: getFullSiteTitle('FAQ'),
      description: () => `Frequently Asked Questions (FAQ) about ${lguName.value}'s services, processes, and government programs. Find quick answers here.`,
      ogTitle: () => getFullSiteTitle('FAQ'),
      ogDescription: () => `Frequently Asked Questions (FAQ) about ${lguName.value}'s services, processes, and government programs. Find quick answers here.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}faq`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('FAQ'),
      twitterDescription: () => `Frequently Asked Questions (FAQ) about ${lguName.value}'s services, processes, and government programs. Find quick answers here.`,
    },
    'budget': {
      title: getFullSiteTitle('Budget & Transparency'),
      description: () => `Explore the budget and transparency reports of ${lguName.value}. Learn how public funds are allocated and utilized.`,
      ogTitle: () => getFullSiteTitle('Budget & Transparency'),
      ogDescription: () => `Explore the budget and transparency reports of ${lguName.value}. Learn how public funds are allocated and utilized.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}budget`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Budget & Transparency'),
      twitterDescription: () => `Explore the budget and transparency reports of ${lguName.value}. Learn how public funds are allocated and utilized.`,
    },
    'government-index': {
      title: getFullSiteTitle('Government'),
      description: () => `Meet the leadership and offices serving ${lguName.value}. View the executive, legislative, and department heads of the ${labels.value.lguTypeLabel}.`,
      ogTitle: () => getFullSiteTitle('Government'),
      ogDescription: () => `Meet the leadership and offices serving ${lguName.value}. View the executive, legislative, and department heads of the ${labels.value.lguTypeLabel}.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}government`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Government'),
      twitterDescription: () => `Meet the leadership and offices serving ${lguName.value}. View the executive, legislative, and department heads of the ${labels.value.lguTypeLabel}.`,
    },
    'history': {
      title: getFullSiteTitle('History'),
      description: () => `Tracing the roots and evolution of our community in ${lguName.value}.`,
      ogTitle: () => getFullSiteTitle('History'),
      ogDescription: () => `Tracing the roots and evolution of our community in ${lguName.value}.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}history`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('History'),
      twitterDescription: () => `Tracing the roots and evolution of our community in ${lguName.value}.`,
    },
    'join-us': {
      title: getFullSiteTitle('Join Us'),
      description: () => `Be part of the movement for transparent and accessible governance data in ${lguName.value}.`,
      ogDescription: () => `Be part of the movement for transparent and accessible governance data in ${lguName.value}.`,
      ogType: 'website',
      ogTitle: () => getFullSiteTitle('Join Us'),
      ogUrl: () => `${getOpenGraphUrl()}join-us`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Join Us'),
      twitterDescription: () => `Be part of the movement for transparent and accessible governance data in ${lguName.value}.`,
    },
    'privacy': {
      title: getFullSiteTitle('Privacy Policy'),
      description: () => `Privacy Policy of ${lguName.value}. Learn how we protect, collect, and use your personal information.`,
      ogDescription: () => `Privacy Policy of ${lguName.value}. Learn how we protect, collect, and use your personal information.`,
      ogType: 'website',
      ogTitle: () => getFullSiteTitle('Privacy Policy'),
      ogUrl: () => `${getOpenGraphUrl()}privacy`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Privacy Policy'),
      twitterDescription: () => `Privacy Policy of ${lguName.value}. Learn how we protect, collect, and use your personal information.`,
    },
    'terms': {
      title: getFullSiteTitle('Terms of Use'),
      description: () => `Terms of Use for the Official Portal of ${lguName.value}. Read our policies, guidelines, and terms.`,
      ogTitle: () => getFullSiteTitle('Terms of Use'),
      ogDescription: () => `Terms of Use for the Official Portal of ${lguName.value}. Read our policies, guidelines, and terms.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}terms`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Terms of Use'),
      twitterDescription: () => `Terms of Use for the Official Portal of ${lguName.value}. Read our policies, guidelines, and terms.`,
    },
    'tourism': {
      title: getFullSiteTitle('Tourism'),
      description: () => `Explore the beauty, culture, and hospitality of ${lguName.value}. Discover local attractions and vibrant festivals.`,
      ogTitle: () => getFullSiteTitle('Tourism'),
      ogDescription: () => `Explore the beauty, culture, and hospitality of ${lguName.value}. Discover local attractions and vibrant festivals.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}tourism`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Tourism'),
      twitterDescription: () => `Explore the beauty, culture, and hospitality of ${lguName.value}. Discover local attractions and vibrant festivals.`,
    },
    'news-index': {
      title: getFullSiteTitle('News & Announcements'),
      description: () => `Stay updated with the latest news, announcements, and press releases from the ${labels.value.lguTypeLabel} of ${lguName.value}.`,
      ogTitle: () => getFullSiteTitle('News & Announcements'),
      ogDescription: () => `Stay updated with the latest news, announcements, and press releases from the ${labels.value.lguTypeLabel} of ${lguName.value}.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}news`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('News & Announcements'),
      twitterDescription: () => `Stay updated with the latest news, announcements, and press releases from the ${labels.value.lguTypeLabel} of ${lguName.value}.`,
    },
    'legislative-index': {
      title: getFullSiteTitle('Legislative'),
      description: () => `Ordinances and resolutions of the ${labels.value.legislativeBody} ng ${lguName.value}.`,
      ogTitle: () => getFullSiteTitle('Legislative'),
      ogDescription: () => `Ordinances and resolutions of the ${labels.value.legislativeBody} ng ${lguName.value}.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}legislative`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Legislative'),
      twitterDescription: () => `Ordinances and resolutions of the ${labels.value.legislativeBody} ng ${lguName.value}.`,
    },
    'legislative-ordinance-framework': {
      title: getFullSiteTitle('Ordinance Framework'),
      description: () => `${labels.value.deptPrefix} ordinances enacted by the ${labels.value.legislativeBody} of ${lguName.value}.`,
      ogTitle: () => getFullSiteTitle('Ordinance Framework'),
      ogDescription: () => `${labels.value.deptPrefix} ordinances enacted by the ${labels.value.legislativeBody} of ${lguName.value}.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}legislative/ordinance-framework`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Ordinance Framework'),
      twitterDescription: () => `${labels.value.deptPrefix} ordinances enacted by the ${labels.value.legislativeBody} of ${lguName.value}.`,
    },
    'legislative-resolution-framework': {
      title: getFullSiteTitle('Resolution Framework'),
      description: () => `Resolutions passed by the ${labels.value.legislativeBody} of ${lguName.value}.`,
      ogTitle: () => getFullSiteTitle('Resolution Framework'),
      ogDescription: () => `Resolutions passed by the ${labels.value.legislativeBody} of ${lguName.value}.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}legislative/resolution-framework`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Resolution Framework'),
      twitterDescription: () => `Resolutions passed by the ${labels.value.legislativeBody} of ${lguName.value}.`,
    },
    'services-index': {
      title: getFullSiteTitle('Services'),
      description: () => `Browse and access all public services provided by the local government of ${lguName.value}.`,
      ogTitle: () => getFullSiteTitle('Services'),
      ogDescription: () => `Browse and access all public services provided by the local government of ${lguName.value}.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}services`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Services'),
      twitterDescription: () => `Browse and access all public services provided by the local government of ${lguName.value}.`,
    },
    'sitemap': {
      title: getFullSiteTitle('Sitemap'),
      description: () => `Complete sitemap of Better ${lguName.value} — find all pages, services, and government resources available on this portal.`,
      ogTitle: () => getFullSiteTitle('Sitemap'),
      ogDescription: () => `Complete sitemap of Better ${lguName.value} — find all pages, services, and government resources available on this portal.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}sitemap`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Sitemap'),
      twitterDescription: () => `Complete sitemap of Better ${lguName.value} — find all pages, services, and government resources available on this portal.`,
    },
    'statistics': {
      title: getFullSiteTitle('Statistics'),
      description: () => `Explore statistics and data on ${lguName.value}'s governance activities. Find insights and trends.`,
      ogTitle: () => getFullSiteTitle('Statistics'),
      ogDescription: () => `Explore statistics and data on ${lguName.value}'s governance activities. Find insights and trends.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}statistics`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Statistics'),
      twitterDescription: () => `Explore statistics and data on ${lguName.value}'s governance activities. Find insights and trends.`,
    },
    'contact': {
      title: getFullSiteTitle('Contact Us'),
      description: () => `Get in touch with the ${labels.value.lguTypeLabel} of ${lguName.value}. Find contact information for various offices and departments.`,
      ogTitle: () => getFullSiteTitle('Contact Us'),
      ogDescription: () => `Get in touch with the ${labels.value.lguTypeLabel} of ${lguName.value}. Find contact information for various offices and departments.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}contact`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Contact Us'),
      twitterDescription: () => `Get in touch with the ${labels.value.lguTypeLabel} of ${lguName.value}. Find contact information for various offices and departments.`,
    },
    'news-slug': {
      title: getFullSiteTitle('News Article'),
      description: () => `Read the latest news and announcements from the ${labels.value.lguTypeLabel} of ${lguName.value}.`,
      ogTitle: () => getFullSiteTitle('News Article'),
      ogDescription: () => `Read the latest news and announcements from the ${labels.value.lguTypeLabel} of ${lguName.value}.`,
      ogType: 'article',
      ogUrl: () => `${getOpenGraphUrl()}news`,
      twitterCard: 'summary_large_image',
      twitterTitle: () => getFullSiteTitle('News Article'),
      twitterDescription: () => `Read the latest news and announcements from the ${labels.value.lguTypeLabel} of ${lguName.value}.`,
    },
    'services-category': {
      title: getFullSiteTitle('Service Category'),
      description: () => `Browse government services by category in ${lguName.value}.`,
      ogTitle: () => getFullSiteTitle('Service Category'),
      ogDescription: () => `Browse government services by category in ${lguName.value}.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}services`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Service Category'),
      twitterDescription: () => `Browse government services by category in ${lguName.value}.`,
    },
    'service-details-slug': {
      title: getFullSiteTitle('Service Details'),
      description: () => `Detailed information about local government services in ${lguName.value}.`,
      ogTitle: () => getFullSiteTitle('Service Details'),
      ogDescription: () => `Detailed information about local government services in ${lguName.value}.`,
      ogType: 'website',
      ogUrl: () => `${getOpenGraphUrl()}services`,
      twitterCard: 'summary',
      twitterTitle: () => getFullSiteTitle('Service Details'),
      twitterDescription: () => `Detailed information about local government services in ${lguName.value}.`,
    },
  }

  return seoData
}
